changelog:
  categories:
    - title: 機能追加
      labels:
        - enhancement
    - title: 不具合修正
      labels:
        - bug
    - title: その他
      labels:
        - etc
        - documentation
    - title: 廃止
      labels:
        - duplicate
  exclude:
    labels:
      - ignore-for-release
      - refactoring
